"""
report.py
Generates a standalone HTML report for a web scan, styled to match the
rest of the portfolio's terminal aesthetic.
"""
import os
import datetime

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Web Scan Report :: {target}</title>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;800&display=swap" rel="stylesheet">
<style>
  :root {{ --bg:#060a07; --panel:#0b120d; --border:#1c3322; --green:#39ff88; --dim:#6f9c81; --red:#ff4d5e; --amber:#ffd166; --text:#d5f5e0; }}
  * {{ box-sizing:border-box; }}
  body {{ background:var(--bg); color:var(--text); font-family:'JetBrains Mono',monospace; padding:32px; max-width:900px; margin:0 auto; }}
  h1 {{ color:var(--green); font-size:22px; }}
  .meta {{ color:var(--dim); font-size:13px; margin-bottom:24px; }}
  table {{ width:100%; border-collapse:collapse; font-size:13px; }}
  th {{ text-align:left; color:var(--dim); text-transform:uppercase; font-size:11px; padding:8px 4px; border-bottom:1px solid var(--border); }}
  td {{ padding:8px 4px; border-bottom:1px solid rgba(28,51,34,0.5); }}
  .sev-HIGH {{ color:var(--red); font-weight:700; }}
  .sev-MEDIUM {{ color:var(--amber); font-weight:700; }}
  .footer {{ color:var(--dim); font-size:11px; margin-top:24px; }}
</style>
</head>
<body>
  <h1>&gt; web_scan_report.log</h1>
  <div class="meta">target: {target} &nbsp;·&nbsp; scanned_at: {scanned_at} &nbsp;·&nbsp; findings: {count}</div>
  <table>
    <thead><tr><th>severity</th><th>check</th><th>detail</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
  <div class="footer">Generated by Web Vulnerability Scanner · for authorized testing only</div>
</body>
</html>
"""


def generate_html_report(results, findings, out_dir=None):
    out_dir = out_dir or os.path.join(os.path.dirname(__file__), "..", "reports")
    os.makedirs(out_dir, exist_ok=True)

    rows = "".join(
        f"<tr><td class='sev-{f['severity']}'>{f['severity']}</td><td>{f['check']}</td><td>{f['detail']}</td></tr>"
        for f in findings
    ) or "<tr><td colspan='3'>No findings</td></tr>"

    html = TEMPLATE.format(
        target=results["target"], scanned_at=results["scanned_at"], count=len(findings), rows=rows
    )

    safe_name = results["target"].replace("://", "_").replace("/", "_")
    filename = f"webscan_{safe_name}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    path = os.path.join(out_dir, filename)
    with open(path, "w") as f:
        f.write(html)
    return path
